config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   resources :words
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
	validates :title, presence: true, length: { minimum: 3 }
	validates :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

	def index
		@words = Word.all.order('created_at DESC')
	end

	def new
		@word = Word.new
	end

	def create
		@word = Word.new(word_params)
		
		if @word.save
			redirect_to @word
		else
			render 'new'
		end
	end

	def show
		@word = Word.find(params[:id])
		@random_number = Random.rand(100)
	end

	def random_word
		@random_number = Random.rand(999)

	end


	private

		def word_params
			params.require(:word).permit(:title, :category)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamGame !!!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/index.html.erb
<h1> This is the famGame index page </h1>
<% @words.each do |word| %>
	<div class="word_wrapper">
		<h2 class="category"> <%= link_to word.category, word %> </h2>
		<h2 class="title"> <%= link_to word.title, word %> </h2>
		<p class="date"> <%= time_ago_in_words(word.created_at) %> </p>
	</div>
<% end %>

app/views/words/new.html.erb
<h1> Enter your own word! </h1>

	<%= form_for :word, url: words_path do |f| %>
		<!-- Block to handle errors while saving posts -->
		<% if @word.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@word.errors.count, "error") %> stopped this word from saving </h2>
				<ul>
					<% @word.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
	
		<p>
			<%= f.label :category %> <br>
			<%= f.text_field :category %>		
		</p>

		<p>
			<%= f.label :word %> <br>
			<%= f.text_field :title %>		
		</p>

		<p>
			<%= f.submit %>
		</p>

	<% end %>

app/views/words/show.html.erb
<div id="word_content">	
	<h1 class="title">
		<%= @word.category %>
		<%= @random_number %>
	</h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@word.created_at) %> ago |
		<%= link_to 'Edit', edit_word_path(@word) %>
	</p>

	<p class="body">
		<%= @word.title %>
	</p>
</div>